# Generated by Django 4.0.2 on 2022-02-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('price', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('color', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('storage', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('model', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('company', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('year', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('imageFront', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('imageModalfirst', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('imageModalsecond', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('imageModalthrid', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
