# Generated by Django 4.0.2 on 2022-02-25 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='description',
            field=models.CharField(blank=True, default='', max_length=800, null=True),
        ),
    ]
