# Generated by Django 4.0.2 on 2022-02-25 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0002_alter_phone_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='imageModalfirst',
            new_name='amazon',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='imageModalsecond',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='imageModalthrid',
            new_name='video',
        ),
    ]
